### ISSUE TITLE
typing.Final is new in version Python 3.8

### ISSUE THREAD

**Issue by simonod85** [DCSO/dcso-portal-python-sdk#4]
As described in requirements:
Python v3.7 or greater

But typing.Final is new in version Python 3.8:
https://docs.python.org/3/library/typing.html#typing.Final

```
File "/root/dcso-portal-python-sdk-main/lib/dcso/glosom/constants.py", line 3, in <module>
    from typing import Final
ImportError: cannot import name 'Final' from 'typing' (/usr/local/lib/python3.7/typing.py)
```

Splunk versions 8.x supports Python 3.7:
https://docs.splunk.com/Documentation/Splunk/8.1.0/Python3Migration/AboutMigration

**Comment by geertjanvdk** [comment]
Yes, that is not correct. I know what happened there, and we will remove that line.
